version: '3.9'
services:
  emitter:
    build: emitter
    container_name: emitter
    ports:
      - "8080:8080"
    depends_on:
      mongostorage:
        condition: service_healthy

  api:
    build: api
    container_name: api
    ports:
      - "8090:8080"
    depends_on:
      mongostorage:
        condition: service_healthy

  # https://github.com/docker-library/mongo/issues/339#issuecomment-1166441526
  # mongo with replica set
  mongostorage:
    hostname: mongo1
    image: mongo:latest
    container_name: mongostorage
    environment:
      - AUTH=no # without password
    ports:
      - 27017:27017
    volumes:
      - ./mngreplica.key:/data/replica.key # openssl rand -base64 756 > mngreplica.key && chmod 400 mngreplica.key
      - ./mongo-init2.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mngdata:/data/db
    command: [mongod, --replSet, 'jamRS', --noauth, --maxConns, "10000"]
    healthcheck:
      test: mongo /mongo-init.js
      interval: 5s
    # entrypoint:
    #     - bash
    #     - -c
    #     - |
    #         cp /data/replicaset.key.devel /data/replicaset.key
    #         chmod 400 /data/replica.key
    #         chown 999:999 /data/replica.key
    #         exec docker-entrypoint.sh $$@     
    # command: "mongod --bind_ip_all --replSet replicaSet01 --keyFile /data/replica.key"