version: '2'
services:

  api:
    build: api
    container_name: api
    ports:
      - "8080:8080"
    # depends_on:
    #   database:
    #     condition: service_healthy

  mongostorage:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: jamgg
      MONGO_INITDB_ROOT_PASSWORD: jam
    ports:
      - 27017:27017
    volumes:
      - ./mngdata:/data/db